CREATE TABLE SAILORS(
 Sid INT PRIMARY KEY,
 Sname CHAR(30),
 Rating FLOAT,
 Age INT);
INSERT INTO SAILORS (Sid , Sname , Rating , Age) VALUES 
			(10245,"JACK",4.8,47),
			(104567,"BOB",3.9,41),
			(105857,"JOHN",4.5,43);

 CREATE TABLE BOATS(
  Bid INT PRIMARY KEY,
  Bname CHAR(30),
  Colour CHAR(15));
 INSERT INTO BOATS (Bid , Bname , Colour) VALUES 
			(101,"GEORGE","RED"),
			(103,"JACOB","BLUE"),
			(105,"JAMES","YELLOW");

  CREATE TABLE RESERVES(
  Sid INT,
  Bid INT,
  Day DATE);
INSERT INTO RESERVES (Sid , Bid , Day) VALUES 
			(20456,101,2021-01-25),
			(203789,103,2021-01-24),
			(207383,105,2021-01-25),
			(204557,105,2021-01-24);


SELECT A.Sid, A.Sname, A.Rating, A.Age
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.Sid = C.Sid AND C.Bid = 101;

SELECT B.Bname
FROM RESERVES AS C
INNER JOIN SAILORS AS A ON A.Sid =C.Sid AND A.Sname= 'BOB'
INNER JOIN BOATS AS B ON B.Bid=C.Bid;

SELECT A.Sname
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.Sid = C.Sid
INNER JOIN BOATS AS B ON B.Bid = C.Bid AND B.Colour = 'RED'
ORDER BY A.Age;

SELECT DISTINCT A.Sname
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.Sid IN (C.Sid);

SELECT A.Sid , A.Sname
FROM RESERVES AS C
INNER JOIN RESERVES AS D ON C.Sid <> D.Sid AND C.Day=D.Day
INNER JOIN SAILORS AS A ON D.Sid=A.Sid;
DROP TABLE SAILORS;
